### ISSUE TITLE
I can't run these code successfully

### ISSUE THREAD

**Issue by Xiao-Zhanpeng** [nadhirfr/rf-ids#3]
I wanna know what Python version did you use? I can't run these code.

![image](https://user-images.githubusercontent.com/22396985/79337299-d0315e00-7f57-11ea-9d96-46a37543bab5.png)
![image](https://user-images.githubusercontent.com/22396985/79337324-dd4e4d00-7f57-11ea-8e2a-3581b348af86.png)

**Comment by nadhirfr** [comment]
Hello,

It looks like you haven't added the model to the directory, so the pickle failed to load the file. 
Or there might be the pickle version are different between serialized model and installed.

**Comment by shubhamdhingra38** [comment]
How are you capturing the data packets in this project?

**Comment by aturker1** [comment]
Hello,
I was getting same error, i solved it with downloading manually the file 'rf-ids/mysite/app/includes/rf_gridcv_tanpa_scaler_100-est-log2.pkl'.
